name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: check style
        run: yarn run check:style
