# Publish new commits to npm. See https://github.com/mikeal/merge-release/blob/master/README.md for more info. 

name: Publish

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: mikeal/merge-release@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
